#!/usr/bin/env python3

import os
import sys
import re
from helpers import createFileList, checkCwd

def createTagFiles(filelist):
    # this function reads the first line (Title) and last line (tags)
    # from each file and creates tag files that link to the respective
    # target file
    if '.tags' not in os.listdir():
        # we should be inside the knowledgebase root folder by now
        # if not, something broke, sorry ...
        print('tags directory not found, creating')
        os.mkdir('.tags')
    os.chdir('.tags')

    # delete existing tag files
    for f in os.listdir():
        if f.endswith('.md'):
            os.remove(f)

    taglist = {}

    for f in filelist:
        h = open(f, 'r')
        lines = h.readlines()
        h.close()
        header_wrong = False
        trailer_wrong = False
        # check if first non-empty line starts with a heading
        for l in lines:
            if len(l.strip()) == 0:
                # line is empty, check next line
                continue
            if not l.strip().startswith('#'):
                header_wrong = True
            break
        
        # check if last non-empty line is a tags: line
        for l in lines[::-1]:
            if len(l.strip()) == 0:
                # line is empty, check previous line
                continue
            if not l.strip().startswith('tags:'):
                trailer_wrong = True
            break

        if header_wrong or trailer_wrong:
            # if the file we just read doesn't have a heading at the start and a line
            # starting with tags: at the end, we don't want to build an index for it
            print("%s doesn't follow the formatting rules, skipping..." % f)
            continue

        title = lines[0].strip().lstrip('#')  # every file starts with a title, remove leading # and whitespaces

        tagline = lines[-1].strip().lstrip('tags:')  # last line contains the tags
        tags = [tag.lower() for tag in re.findall("\[(.*?)]", tagline)]  # find all tags inside []
        tagline = re.sub("\[.*?]", "", tagline)  # remove tags inside [], replace them with space

        tags.extend([tag.lower() for tag in tagline.split()])  # finally get the remaining tags

        for tag in tags:
            if tag in taglist.keys():
                taglist[tag].append((title, f))
            else:
                taglist[tag] = [(title, f)]

    for tag in taglist.keys():
        h = open(tag.lstrip('#') + '.md', 'w')
        h.write('# Notes tagged with #%s\n' % tag.lstrip('#'))
        for title, filename in taglist[tag]:
            h.write("[{}]({})\n".format(title.strip(), filename))
        h.close()


def main():
    checkCwd()
    filelist = createFileList()

    try:
        # turn the links into relative paths
        filelist = [f.replace(os.environ['KBHOME'], '../') for f in filelist]
    except KeyError:
        # $KBHOME is not set
        pass
    createTagFiles(filelist)


if __name__ == '__main__':
    main()
